version: 2
jobs:
  test:
    docker:
    - image: circleci/php:7.2.17-stretch
    steps:
    - checkout
    - run: composer validate
    - run: composer install
workflows:
  version: 2
  workflow:
    jobs:
    - test:
        filters:
          branches:
            only:
            - master
